### PR TITLE
test

### PR DESCRIPTION
**Pull request by GrantBirki**
testing -> https://github.com/github/branch-deploy/pull/117

### CODE REVIEW

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
Now I'm going to test with `update_branch: disabled` set

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
testing with `update_branch: force`

**Comment by GrantBirki** [comment]
.deploy

**Comment by KevinMSampson** [comment]
@GrantBirki 

Hi! I'm wondering if the version of GHES (3.6.2) used may be a factor. If you can re-run with debug logs I can do a more detailed comparison between your run logs and my own tomorrow to try and get a clearer picture.

**Comment by GrantBirki** [comment]
@KevinMSampson Of course! Let me know which job you would like me to re-run (link) and I'll do so with debugging enabled. Thanks!

**Comment by KevinMSampson** [comment]
@GrantBirki the 2nd deploy run in this PR would be great to debug compare (normal deployment with warn enabled)

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
@KevinMSampson I have re-run the CI job for `.deploy` with `update_branch: warn` set

Here are the [actions log](https://github.com/GrantBirki/actions-sandbox/actions/runs/4400024581/jobs/7704950781) for that command with debug mode **enabled**

> Please note this was done with `github/branch-deploy@v4.6.0`

**Comment by GrantBirki** [comment]
@KevinMSampson I would also suggest opening a new issue in the [github/branch-deploy](https://github.com/github/branch-deploy/issues/new/choose) repo as I don't actively monitor this repo all that much as its just for me testing around with Actions and the sorts. Thanks! ⭐

**Comment by GrantBirki** [comment]
.lock

**Comment by GrantBirki** [comment]
.lock

**Comment by GrantBirki** [comment]
.wcid

**Comment by GrantBirki** [comment]
.lock

**Comment by GrantBirki** [comment]
.lock production

**Comment by GrantBirki** [comment]
.unlock

**Comment by GrantBirki** [comment]
.wcid

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.lock

**Comment by GrantBirki** [comment]
.deploy noop production

**Comment by GrantBirki** [comment]
.deploy noop development

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy development

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by GrantBirki** [comment]
.deploy to staging

**Comment by GrantBirki** [comment]
.deploy to staging

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by GrantBirki** [comment]
.deploy

**Pull request closed without merging**
